export const ACTION_TYPES = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  AUTH_FAILURE: 'AUTH_FAILURE',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SET_AUTH_LOADING_STATE: 'SET_AUTH_LOADING_STATE',
  SET_PROJECTS_LOADING_STATE: 'SET_PROJECTS_LOADING_STATE',
  PROJECTS_FAILURE: 'PROJECTS_FAILURE',
  SET_ALL_PROJECTS: 'SET_ALL_PROJECTS',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
}
